apiVersion: apps/v1
kind: Deployment
metadata:
  name: studbase-backend
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: studbase
  template:
    metadata:

      labels:
        app: studbase

    spec:
      volumes:
        - name: gcp-service-account-volume
          secret:
            secretName: gcp-service-account
            defaultMode: 420
      containers:
        - name: studbase
          image: us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend
          ports:
            - containerPort: 9098
              protocol: TCP
          envFrom:
            - secretRef:
                name: studbase-secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp/sa.json
          volumeMounts:
            - name: gcp-service-account-volume
              readOnly: true
              mountPath: /var/secrets/gcp
          imagePullPolicy: Always
      restartPolicy: Always

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

