name: Maven Deploy

on:
  push:
    branches:
      - main
      - pipeline # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Maven Repository
    runs-on: ubuntu-latest

    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} # Define the environment variable using secrets

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: build
        run: docker build -t us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest .

      - name: Decode and write GCP service account key to file
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > /home/runner/gcloud-key.json
          echo "$GCP_SERVICE_ACCOUNT_KEY"
          cat /home/runner/gcloud-key.json
        shell: /usr/bin/bash -e {0}

      - name: docker login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: auth
        run: gcloud auth activate-service-account runners@studentbase-v1.iam.gserviceaccount.com --key-file=/home/runner/gcloud-key.json --project=studentbase-v1

      - name: push
        run: docker push us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest
      - name: deploy
        run: |
          ls /home/runner/scripts  # Verify if the directory contains the deploy.yml file
           kubectl apply -f /home/runner/scripts/deploy.yml
