name: Maven Deploy

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  deploy:
    name: Deploy to Maven Repository
    runs-on: ubuntu-latest

    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: build
        run: docker build -t us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest .

      - name: Decode and write GCP service account key to file
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > /home/runner/gcloud-key.json
          echo "$GCP_SERVICE_ACCOUNT_KEY"
          cat /home/runner/gcloud-key.json

      - name: Install gcloud SDK
        run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
          tar xzf google-cloud-sdk.tar.gz
          ./google-cloud-sdk/install.sh

      - name: Install kubectl
        run: |
           sudo apt-get update && sudo apt-get install -y kubectl
           sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin

      - name: Authenticate gcloud
        run: |
          gcloud auth activate-service-account runners@studentbase-v1.iam.gserviceaccount.com --key-file=/home/runner/gcloud-key.json --project=studentbase-v1
          gcloud config set project studentbase-v1
          gcloud config set compute/zone us-central1-a

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials student-base-cluster --region us-central1-c

      - name: docker login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: push
        run: docker push us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest

      - name: deploy
        run: |
          ls
          kubectl apply -f scripts/deploy.yml --validate=false

