name: Maven Deploy

on:
  push:
    branches:
      - master
      - pipeline # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Maven Repository
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: build
        run: docker build -t us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest .

      - name: Decode and write GCP service account key to file
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        run: echo "$GCP_SERVICE_ACCOUNT_KEY"  > $HOME/gcloud-key.json

      - name: auth 
        run: |
          cat $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project studentbase-v1

      - name: auth-2
        run: gcloud auth activate-service-account runners@studentbase-v1.iam.gserviceaccount.com --key-file=$HOME/gcloud-key.json --project=studentbase-v1

      - name: push
        run: docker push us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest

      - name: deploy
        run: kubectl apply -f ./scripts/deploy.yml
