name: Maven Deploy

on:
  push:
    branches:
      - main 
      - new # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Maven Repository
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: build
        run: docker build -t us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest .

      - name: Deploy to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=./scripts/sa.json
          gcloud config set project studentbase-v1 

      - name: auth
        run: gcloud auth activate-service-account runners@studentbase-v1.iam.gserviceaccount.com --key-file=./scripts/sa.json --project=studentbase-v1
      - name: push
        run: docker push us-central1-docker.pkg.dev/studentbase-v1/studentbase/backend:latest

      - name: deploy
        run: kubectl apply -f ./scripts/deploy.yml
